### ISSUE TITLE
Best way to set dom-specific values?

### ISSUE THREAD

**Issue by Bkucera** [arqex/react-interactable#1]
First, thanks for this lib.
I ported over `react-spring`'s draggable-list to `react-interactable` with good results:
https://codesandbox.io/s/react-interactable-draggable-list-pmwdw

but had to make a small hack to set `zIndex` on the elements (see `onDrag` prop)

Would you recommend any better way of doing this other than `ReactDOM.findDOMNode`?

I know we shouldn't break the compatibility between this and react-native-interactable, and I'm not sure there would be a clear way to port this example to native

**Comment by arqex** [comment]
Hey Ben!

Glad you liked the library. I don't have my computer with me now, but I'll
have a look on Monday. I'm open to make changes to make it easier to work
with z indexes.

**Comment by Bkucera** [comment]
Ok, I've found a working solution. I can just use an animated value on the InteractableView itself:
```js
const zIndex = new Animated.Value(0)
return (
<Interactable.View>
  style={{zIndex}}
</Interactable.View>
)
```
then I can use `zIndex.setValue(1)` to set zindex on the parent. I did notice a bug with setting `style.transform` on `Interactable.View` however, and have opened a PR
